apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "lab05.name" . }}-secret'
type: Opaque
data:
  DRUPAL_DATABASE_HOST: '{{ printf "%s-%s" .Release.Name "mariadb" | b64enc }}'
  DRUPAL_DATABASE_PORT_NUMBER: '{{ .Values.mariadb.primary.service.ports.mysql | toString | b64enc }}'
  DRUPAL_DATABASE_USER: '{{ .Values.mariadb.auth.username | b64enc }}'
  DRUPAL_DATABASE_NAME: '{{ .Values.mariadb.auth.database | b64enc }}'
  DRUPAL_DATABASE_PASSWORD: '{{ .Values.mariadb.auth.password | b64enc }}'
  ALLOW_EMPTY_PASSWORD: '{{ "yes" | b64enc }}'
  BITNAMI_DEBUG: '{{ "true" | b64enc }}'
